# Targets

[[target]]
name = "gsim"
description = "General-purpose GHDL simulations"
command = "python"
args = ["targets/gsim.py"]

[[target]]
name = "vsim"
description = "General-purpose verilator simulations"
command = "python"
args = ["targets/vsim.py"]

[[target]]
name = "msim"
description = "General-purpose modelsim simulations"
command = "python"
args = ["targets/msim.py"]
fileset.do = "{{orbit.bench}}.do"

[[target]]
name = "quartz"
description = "Intel quartus prime toolflow"
command = "python"
args = ["targets/quartz.py"]
fileset.board = "*.board.toml"
fileset.bdf = "*.bdf"

[[target]]
name = "voodoo"
description = "Vivado non-project mode toolflow"
command = "python"
args = ["targets/voodoo.py"]
fileset.xdcf = "*.xdc"

[[target]]
name = "xpro"
description = "Vivado project mode toolflow"
command = "python"
args = ["targets/xpro.py"]
fileset.xdcf = "*.xdc"

# Protocols

[[protocol]]
name = "git"
description = "Handle remote repositories with git"
command = "git"
args = ["clone", "-b", "{{orbit.ip.version}}", "{{orbit.ip.source.url}}"]