# Profile: Hyperspace Labs
# File: config.toml
#
# Configurations for targets and protocols with orbit.

[[target]]
name = "quartz"
description = "End-to-end fpga toolflow with intel quartus prime"
command = "python"
args = ["targets/quartz.py"]
fileset.board = "*.board.toml"
fileset.bdf = "*.bdf"

[[target]]
name   = "gsim"
description = "Simulations with ghdl"
command = "python"
args    = ["targets/gsim.py"]

[[target]]
name = "veri"
description = "Run tests with verilator"
command = "python"
args = ["targets/veri.py"]

[[target]]
name = "msim"
description = "Run tests with modelsim"
command = "python"
args    = ["targets/msim.py"]
fileset.do = "{{ orbit.bench }}.do"

[[protocol]]
name = "zip"
description = "Handle zip files with requests"
command = "python"
args = ["./protocols/zip.py", "{{ orbit.ip.source.url }}"]

[[protocol]]
name = "git"
description = "Handle remote repositories with git"
command = "git"
args = ["clone", "-b", "{{ orbit.ip.version }}", "{{ orbit.ip.source.url }}"]