[[target]]
name = "gsim"
description = "GHDL general-purpose simulations"
command = "python"
args = ["scripts/gsim.py"]

[[target]]
name = "msim"
description = "ModelSim general-purpose simulations"
command = "python"
args = ["scripts/msim.py"]
fileset.do = "{{orbit.bench}}.do"

[[target]]
name = "quartz"
description = "Intel Quartus Prime toolflow"
command = "python"
args = ["scripts/quartz.py"]
fileset.board = "*.board.toml"
fileset.bdf = "*.bdf"

[[target]]
name = "voodoo"
description = "Xilinx Vivado non-project mode toolflow"
command = "python"
args = ["scripts/voodoo.py"]
fileset.xdcf = "*.xdc"

[[target]]
name = "xpro"
description = "Xilinx Vivado project mode toolflow"
command = "python"
args = ["scripts/xpro.py"]
fileset.xdcf = "*.xdc"
